- README.md
- atlassian_jwt_auth/__init__.py
- atlassian_jwt_auth/algorithms.py
- atlassian_jwt_auth/key.py
- atlassian_jwt_auth/signer.py
- atlassian_jwt_auth/tests/test_key.py
- atlassian_jwt_auth/tests/test_signer.py
- atlassian_jwt_auth/tests/test_verifier.py
- atlassian_jwt_auth/tests/utils.py
- atlassian_jwt_auth/verifier.py
- Remove relative imports
- Only import modules, not classes or functions
- Expose public classes through factory functions in __init__.py
> Clean up imports to follow google python style guides

- README.md
- atlassian_jwt_auth/contrib/requests.py
- atlassian_jwt_auth/contrib/tests/test_requests.py
JWTAuth adds the ability for the `requests` library to
automatically generate ASAP-compatible JWT tokens and add
the header to the request.
```python
from atlassian_jwt_auth.contrib.requests import JWTAuth
response = requests.get(
'https://your-url
auth=JWTAuth('audience', 'isuuer', 'issuer/key', private_key_pem)
)
```
More information: http://docs.python-requests.org/en/latest/user/authentication/
> Added a auth module for the requests HTTP library

- atlassian_jwt_auth/contrib/requests.py
- atlassian_jwt_auth/contrib/tests/test_requests.py
> Sem-Ver: feature support passing through kwargs for the signer created in create_jwt_auth.

- atlassian_jwt_auth/contrib/flask_app/decorators.py
- atlassian_jwt_auth/contrib/flask_app/utils.py
- atlassian_jwt_auth/contrib/tests/test_flask.py
So... it looks like Flask configuration values are usually referenced as `app.config['MY_VAL']` instead of `app.config.my_val`. I based my initial version of the Flask stuff on faulty assumptions based on a bad example.
This PR fixes that by referencing the values properly.
> Fix an issue where Flask config values were not referenced properly

- atlassian_jwt_auth/key.py
- atlassian_jwt_auth/tests/test_public_key_provider.py
> Sem-Ver: bugfix HTTPSPublicKeyRetriever should raise a ValueError if the base_url is None.

- atlassian_jwt_auth/contrib/flask_app/decorators.py
- atlassian_jwt_auth/contrib/tests/test_flask.py
- atlassian_jwt_auth/contrib/tests/utils.py
- atlassian_jwt_auth/key.py
This PR makes testing with Flask MUCH easier by adding an optional ASAP_KEY_RETRIEVER_CLASS setting to specify a class that can be used instead of the default for retrieving public keys.
> Add better settings for test

- atlassian_jwt_auth/contrib/requests.py
- atlassian_jwt_auth/contrib/tests/test_requests.py
This PR contains a minor change to allow passing in additional claims via `**kwargs` to `contrib.requests.JWTAuth`. As far as I can tell, there is currently no other way to do this, unless I'm missing something. /cc @dbaxa
> Allow to pass in additional claims to contrib.requests.JWTAuth

- atlassian_jwt_auth/contrib/django/decorators.py
- atlassian_jwt_auth/contrib/tests/django/test_django.py
The Django decorator was looking in request.META for AUTHORIZATION. In
Django, all headers are capitalized, then prepended with HTTP_AUTHORIZATION.
The client library made an incorrect assumption which ended up in the tests
as well. This fixes the cause, and the tests to use the correct header name.
> Fix decorator for Django

- atlassian_jwt_auth/contrib/django/decorators.py
- atlassian_jwt_auth/contrib/tests/django/test_django.py
When using the default value in the `requires_asap` decorator, the
`split(b'')` call fails in Python 3 because bytes != str. This change just
sets the default value to a bytes instead of a str.
> Fix Python 3 issue with default value

- .mailmap
- AUTHORS
Before:
```
$ git shortlog -s -e
1  Cameron Stewart <cstewart@atlassian.com>
6  David Black <dbaxa@users.noreply.github.com>
158  David Black <dblack@atlassian.com>
5  David Black [Atlassian] <dblack@atlassian.com>
3  James Bunton <jbunton@atlassian.com>
1  Jeremy Shoemaker <jeremy@codingkoi.com>
2  Marcus Bertrand <digimarc@gmail.com>
1  Mark Adams <madams@atlassian.com>
4  Mark Adams <mark@markadams.me>
1  Oleksandr Fedorov <a.g.fedorof@gmail.com>
1  Waldemar Hummer <hummer@infosys.tuwien.ac.at>
```
After:
```
$ git shortlog -s -e
1  Cameron Stewart <cstewart@atlassian.com>
169  David Black <dblack@atlassian.com>
3  James Bunton <jbunton@atlassian.com>
1  Jeremy Shoemaker <jeremy@codingkoi.com>
2  Marcus Bertrand <digimarc@gmail.com>
7  Mark Adams <madams@atlassian.com>
1  Oleksandr …
```
> Add .mailmap to resolve some duplicate identities

- atlassian_jwt_auth/contrib/django/decorators.py
- atlassian_jwt_auth/contrib/tests/django/test_django.py
More issues with string encodings. The requests library seems to force
HTTP headers to be strings even if you give it a bytes so to deal with
that potential ambiguity, we should just explicitly convert any
strings we get in the HTTP_AUTHORIZATION header into bytes before
attempting to parse it further.
> Fix for using requests library in Python 3

- atlassian_jwt_auth/contrib/django/decorators.py
- atlassian_jwt_auth/contrib/django/utils.py
- atlassian_jwt_auth/exceptions.py
- atlassian_jwt_auth/key.py
This also maintains backwards compatibility with existing clients
by keeping ValueError as the base exception.
I also added some logging for Django, but not opposed to splitting that out too.
> Add library exceptions instead of using ValueError

- atlassian_jwt_auth/contrib/tests/test_requests.py
- requirements.txt
> Sem-Ver: bugfix upgrade cryptography from using a version >= 1.8.1 < 1.9.0 to use a version >= 2.0.3 and < 2.1.0.

- atlassian_jwt_auth/contrib/django/middleware.py
Some services will proxy client requests to other services, where client
does not use ASAP and the proxy must rely on other, ASAP-enabled
services to authenticate the client.
To support this, we allow the proxy to add the client's authorization
header as X-ASAP-Authorization. The middleware will then swap
authorization headers before any authorization middleware sees the
request, and swap the headers back before any view-level ASAP checks are
done.
To support anonymous clients, we require a second X-ASAP header before
we swap authorization headers.
> Add Django middleware to auth forwarded clients

- atlassian_jwt_auth/verifier.py
Switched to an OrderedDict to reduce jti lookups from n to log(n).
(cherry picked from commit 39296ce9231c9c51a7f8840afa3c6eb86ea0c213)
> Make _seen_jti a ringbuffer.

- atlassian_jwt_auth/contrib/django/decorators.py
- atlassian_jwt_auth/contrib/django/middleware.py
- atlassian_jwt_auth/contrib/django/utils.py
- atlassian_jwt_auth/contrib/flask_app/decorators.py
- atlassian_jwt_auth/contrib/server/helpers.py
- atlassian_jwt_auth/contrib/tests/django/test_django.py
- atlassian_jwt_auth/contrib/tests/django/urls.py
- atlassian_jwt_auth/contrib/tests/django/views.py
- atlassian_jwt_auth/exceptions.py
Django usually performs authentication in middleware, so that's where we should put ASAP-based authentication. But sometimes per-view authorization needs to occur, so we still need a view decorator to handle this.
`ASAPMiddleware` handles ASAP claim validation, including authentication and global authorization.
`validate_asap` handles per-view authorization, and can optionally reject unauthenticated requests for applications that do not want ASAP enabled globally.
This is also an opportunity to fix an issue with `ASAPForwardedMiddleware`, which will unintuitively run other middleware-based authentication before any ASAP authentication.
> Add better Django ASAP middleware

- requirements.txt
> Sem-Ver: bugfix upgrade cryptography from using a version >= 2.1.3 < 2.2.0 to use a version >= 2.2.1 and < 2.3.0

- atlassian_jwt_auth/key.py
> Sem-Ver: bugfix Use the raw string notation when specifying the key identifier regex

- atlassian_jwt_auth/key.py
- atlassian_jwt_auth/tests/test_public_key_provider.py
> Sem-Ver: bugfix The HTTPSMultiRepositoryPublicKeyRetriever should try the next key repository upon encountering a server error (status code >= 500).

- requirements.txt
> Sem-Ver: bugfix upgrade cryptography from using a version >= 2.2.1 < 2.3.0 to use a version >= 2.3.0 and < 2.4.0

- atlassian_jwt_auth/signer.py
- atlassian_jwt_auth/tests/test_signer.py
> Sem-Ver: bugfix Reduce the time taken to generate a jwt by passing through a load private key instance to jwt.encode.

- atlassian_jwt_auth/contrib/aiohttp/key.py
- atlassian_jwt_auth/key.py
- atlassian_jwt_auth/tests/test_public_key_provider.py
- test-requirements.txt
This change makes it so that when instantiating the HTTPSPublicKeyRetriever class
multiple times, they all share the same requests session with cache.
Previously, each instance would create its own session with isolated cache. Since
the library by default always creates a new instance of the ASAP_KEY_RETRIEVER_CLASS
class (e.g. common.backend.Backend#get_verifier), cached responses were never reused.
> Sem-Ver: api-break Share request sessions across key retriever instances so as to use a common cache.

- atlassian_jwt_auth/frameworks/common/asap.py
- atlassian_jwt_auth/frameworks/django/middleware.py
- atlassian_jwt_auth/frameworks/wsgi/middleware.py
> Sem-Ver: api-break Re-use verifiers in the various middlewares and add an optional verifier argument to the _process_asap_token method.

- requirements.txt
> Sem-Ver: bugfix upgrade cryptography from using a version >= 2.5.0 < 2.6.0 to use a version >= 2.7.0 and < 2.8.0

- requirements.txt
> Sem-Ver: bugfix upgrade cryptography from using a version >= 2.7.0 < 2.8.0 to use a version >= 2.8.0 and < 2.9.0

- atlassian_jwt_auth/frameworks/common/tests/test_utils.py
- atlassian_jwt_auth/frameworks/common/utils.py
> Sem-Ver: feature Allow SettingsDict instances to be hashed.

- test-requirements.txt
> Sem-Ver: bugfix For python 2.7 and 3.5 testing we need to pin itsdangerous to a version < 2.0.0.

- requirements.txt
> Sem-Ver: bugfix upgrade cryptography from using a version >= 2.8.0 < 2.9.0 to use a version >= 3.1.0 and < 3.2.0

- requirements.txt
> Sem-Ver: bugfix upgrade cryptography from using a version >= 3.1.0 < 3.2.0 to use a version >= 3.2.1 and < 3.3.0

- requirements.txt
> Sem-Ver: bugfix upgrade PyJWT from using a version >= 1.5.2 < 2.1.0 to use a version >= 1.5.2 and < 2.2.0

- atlassian_jwt_auth/contrib/tests/aiohttp/test_public_key_provider.py
- atlassian_jwt_auth/contrib/tests/aiohttp/test_verifier.py
> Sem-Ver: bugfix Move away from using asynctest in python versions where unittest async utils are available (3.8 and above).
