atlassian/asap-authentication-python

- atlassian_jwt_auth/verifier.py
> Add the ability to accept a JWT where the subject does not match the issuer.

- requirements.txt
> Sem-Ver: bugfix upgrade cryptography from version 1.1.1 to 1.2.1.

- .travis.yml
- setup.cfg
> Test with python 3.5 in ci.

- setup.py
> Update pbr from version 1.0.1 to 1.8.1.

- setup.py
- test-requirements.txt
> Move test requirements out of setup.py and into test-requirements.txt.

- README.md
Moved install to the top because people generally do that before installing.
Also moved Travis badge to the top and added a Pypi badge.
> Rearranged the README and added badge for pypi

- atlassian_jwt_auth/signer.py
- atlassian_jwt_auth/tests/test_signer.py
> Support providing additional_claims when generating a jwt.

- atlassian_jwt_auth/key.py
- atlassian_jwt_auth/tests/test_public_key_provider.py
> Sem-Ver: feature Add a new HTTPSMultiRepositoryPublicKeyRetriever class which allows using multiple public key repositories.

- requirements.txt
> Sem-Ver: bugfix upgrade PyJWT from version 1.4.2 to use a version >= 1.5.2 but less than 2.0.0.

- README.md
- README.rst
- setup.cfg
I've noticed that the link README refers is broken and fixed it. And then I've noticed that PYPI page has empty description and made pbr add README as long description.
> Readme improvements

- requirements.txt
> Sem-Ver: bugfix upgrade CacheControl from version 0.12.3 to 0.12.4

- atlassian_jwt_auth/tests/test_verifier.py
- atlassian_jwt_auth/verifier.py
> Sem-Ver: feature Support disabling checking if jwt jti are unique.

- atlassian_jwt_auth/frameworks/common/asap.py
> Sem-Ver: bugfix When asap is not required and no asap token has been provided return early in _process_asap_token.

- atlassian_jwt_auth/frameworks/django/middleware.py
> Sem-Ver: bugfix Fix the backend reference in OldStyleASAPMiddleware.

- .travis.yml
- setup.cfg
> Sem-Ver: api-break Drop support for python3.4

- .travis.yml
- atlassian_jwt_auth/contrib/tests/aiohttp/test_public_key_provider.py
- setup.cfg
- test-requirements.txt
> Sem-Ver: feature Add support for python 3.7

- atlassian_jwt_auth/frameworks/wsgi/tests/test_wsgi.py
> Sem-Ver: bugfix Switch the wsgi tests to use unittest assertions.

- atlassian_jwt_auth/exceptions.py
- atlassian_jwt_auth/tests/test_verifier.py
- atlassian_jwt_auth/verifier.py
> Sem-Ver: feature Add and use a specific exception, JtiUniqunessException, for when a JTI is used more than once.

- atlassian_jwt_auth/exceptions.py
- atlassian_jwt_auth/tests/test_verifier.py
- atlassian_jwt_auth/verifier.py
> Sem-Ver: bugfix Fix the spelling of the duplicate jti exception (rename JtiUniqunessException to JtiUniquenessException)

- atlassian_jwt_auth/frameworks/django/tests/test_django.py
- atlassian_jwt_auth/frameworks/flask/tests/test_flask.py
- atlassian_jwt_auth/frameworks/wsgi/tests/test_wsgi.py
- atlassian_jwt_auth/tests/utils.py
> Sem-Ver: bugfix Deduplicate the various framework test create_token methods

- atlassian_jwt_auth/frameworks/common/asap.py
- atlassian_jwt_auth/frameworks/django/tests/test_django.py
- atlassian_jwt_auth/frameworks/flask/tests/test_flask.py
- atlassian_jwt_auth/frameworks/wsgi/tests/test_wsgi.py
> Sem-Ver: bugfix Catch JtiUniquenessException and respond with a 401 inside the frameworks

- atlassian_jwt_auth/frameworks/common/asap.py
> Sem-Ver: feature Add logging to the framework asap token checking code.

- atlassian_jwt_auth/frameworks/django/tests/test_django.py
- atlassian_jwt_auth/frameworks/wsgi/tests/test_wsgi.py
- atlassian_jwt_auth/signer.py
- atlassian_jwt_auth/tests/test_key.py
- atlassian_jwt_auth/tests/test_public_key_provider.py
> Sem-Ver: bugfix Fix some issues that flake8 detected.

- atlassian_jwt_auth/frameworks/common/asap.py
> Sem-Ver: feature Log information on general exceptions in addition to specific exceptions.

- atlassian_jwt_auth/tests/test_verifier.py
- test-requirements.txt
> Sem-Ver: bugfix Add an explicit test for how none algorithm jwt are handled.

- .travis.yml
- setup.cfg
- setup.py
> Sem-Ver: bugfix In CI move to using setup.py nosetests as setup.py test has been deprecated.

- .github/workflows/build.yml
- README.rst
> Sem-Ver: bugfix Add github actions for CI.

- .github/workflows/build.yml
- atlassian_jwt_auth/frameworks/common/backend.py
- atlassian_jwt_auth/signer.py
- atlassian_jwt_auth/tests/test_signer.py
- atlassian_jwt_auth/verifier.py
- requirements.txt
These changes provide support for using PyJWT 1.x and 2.0.x.
> Sem-Ver: feature Add support for using PyJWT 2.0.x

- atlassian_jwt_auth/contrib/aiohttp/key.py
- atlassian_jwt_auth/contrib/tests/aiohttp/test_public_key_provider.py
> Sem-Ver: bugfix The aiohttp public key retriever incorrectly provided a proxies argument when it needed to provide a proxy argument.

- setup.cfg
> Sem-Ver: bugfix Add some missing package metadata information.

- .github/workflows/build.yml
- .travis.yml
- requirements.txt
- setup.cfg
> Sem-Ver: api-break upgrade cryptography from using a version >= 3.3.2 < 3.5.0 to use a version >= 3.3.2 and < 36.0.0

- atlassian_jwt_auth/signer.py
- atlassian_jwt_auth/tests/test_verifier.py
- requirements.txt
> Sem-Ver: api-break upgrade pyjwt from using a version >= 1.5.2 < 2.2.0 to using a version >= 2.2.0 < 2.3.0

- .github/workflows/build.yml
> Sem-Ver: bugfix Stop testing with PyJWT < 2.0.0

- test-requirements.txt
> Sem-Ver: bugfix Update the atlassian-httptest test dep to version 1.0.0

- requirements.txt
Use of a Broken or Risky Cryptographic Algorithm
https://security.snyk.io/vuln/SNYK-PYTHON-PYJWT-2840625
> Sem-Ver: bugfix upgrade pyjwt

- atlassian_jwt_auth/frameworks/common/backend.py
- atlassian_jwt_auth/verifier.py
> Sem-Ver: bugfix Fix two possible memory leaks related to the use of lru_cache on methods.

- .github/workflows/build.yml
- requirements.txt
> Sem-Ver: api-break Have PyJWT specify the version ranges for the cryptography library.
